### ISSUE TITLE
1.19.2 error code 1, no other mods

### ISSUE THREAD

**Issue by AlienLoser** [jacksonhardaway/etched#87]
title says it all. I tested the mod with every mod i have, thinking it could be an issue with just one, but i wanted to see if loading it on its own would work and it didn't. Tried it with all three versions of 1.19.2 and it just crashes with error code 1. I updated my drivers and everything else, it's just crashing to crash, as my other mods load on their own just fine.

**Comment by Ocelot5836** [comment]
Can you provide a log please? What mod loader are you using?

**Comment by AlienLoser** [comment]
sorry for late reply, mod loader im using is forge, log is [here](https://pastebin.com/TRwG8nqU)

**Comment by Ocelot5836** [comment]
you're missing [pollen](https://www.curseforge.com/minecraft/mc-mods/pollen). It's required for all versions prior to 1.20

**Comment by AlienLoser** [comment]
tysm! it wasnt in dependencies so i didnt find it.
